import type { Game } from "./data";

/**
 * Generated by scripts/sync-nfl.mjs.
 * Keep a small checked-in fallback so the site still has schedule data if the
 * upstream feed is temporarily unavailable during a sync run.
 */
export const LIVE_NFL_GAMES: Game[] = [
  ["kansas-city-chiefs","buffalo-bills","2026-10-04","1:00 PM","High","Division battle"],
  ["dallas-cowboys","philadelphia-eagles","2026-10-04","4:25 PM","Premium","Rivalry atmosphere"],
  ["san-francisco-49ers","seattle-seahawks","2026-10-11","8:20 PM","High","Division battle"],
  ["green-bay-packers","chicago-bears","2026-10-18","1:00 PM","Premium","Historic rivalry"],
  ["baltimore-ravens","pittsburgh-steelers","2026-10-25","1:00 PM","Premium","Physical rivalry"],
  ["miami-dolphins","new-york-jets","2026-10-25","1:00 PM","Medium","Division matchup"],
  ["atlanta-falcons","new-orleans-saints","2026-11-08","1:00 PM","High","Division rivalry"],
  ["buffalo-bills","new-england-patriots","2026-11-15","4:25 PM","High","Division matchup"],
  ["denver-broncos","kansas-city-chiefs","2026-11-22","4:05 PM","High","Division battle"],
  ["philadelphia-eagles","new-york-giants","2026-11-29","1:00 PM","Medium","Division matchup"],
  ["detroit-lions","green-bay-packers","2026-12-06","4:25 PM","High","Division battle"],
  ["houston-texans","jacksonville-jaguars","2026-12-13","1:00 PM","Medium","Division matchup"],
  ["los-angeles-rams","san-francisco-49ers","2026-12-20","4:25 PM","High","NFC West matchup"],
  ["cincinnati-bengals","cleveland-browns","2026-12-20","1:00 PM","Medium","In-state rivalry"],
  ["tampa-bay-buccaneers","carolina-panthers","2026-12-27","1:00 PM","Medium","Division matchup"],
  ["minnesota-vikings","detroit-lions","2027-01-03","1:00 PM","High","Division battle"],
  ["arizona-cardinals","los-angeles-rams","2026-10-04","4:05 PM","Medium","NFC West matchup"],
  ["indianapolis-colts","houston-texans","2026-10-11","1:00 PM","High","Division matchup"],
  ["las-vegas-raiders","denver-broncos","2026-10-18","4:05 PM","High","AFC West matchup"],
  ["los-angeles-chargers","kansas-city-chiefs","2026-10-25","4:25 PM","Premium","High-demand matchup"],
  ["tennessee-titans","jacksonville-jaguars","2026-11-08","1:00 PM","Medium","Division matchup"],
  ["washington-commanders","philadelphia-eagles","2026-11-15","1:00 PM","High","NFC East matchup"],
  ["carolina-panthers","detroit-lions","2026-10-04","8:20 PM","High","Sunday Night Football"],
  ["atlanta-falcons","baltimore-ravens","2026-10-11","8:20 PM","High","Sunday Night Football"],
  ["green-bay-packers","dallas-cowboys","2026-10-18","8:20 PM","Premium","Sunday Night Football"],
  ["seattle-seahawks","kansas-city-chiefs","2026-10-25","8:20 PM","Premium","Sunday Night Football"],
].map(([home, away, date, time, demand, reason], index) => ({
  id: `game-${index + 1}`,
  home,
  away,
  date,
  time,
  venue: "",
  city: "",
  demand: demand as Game["demand"],
  reason,
}));
